#!/bin/sh
# Synthetic voice fixtures (docs/12 §9). No real people or patients: every clip is generated by a
# text-to-speech voice. macOS `say` voices: Rishi (en_IN), Lekha (hi_IN). Output: 16 kHz mono PCM16 WAV.
# Odia has no macOS voice; an Odia clip needs a separate, labelled source (see docs/12).
set -eu
cd "$(dirname "$0")"
gen() { say -v "$1" --file-format=WAVE --data-format=LEI16@16000 -o "$2" "$3"; }
gen Rishi en_fever_102.wav "I have had fever for three days. My temperature is 102 degrees Fahrenheit. I do not have chest pain."
gen Rishi en_pulse_oxygen.wav "Pulse is one hundred and twenty. Oxygen is ninety two percent."
gen Lekha hi_fever_102.wav "मुझे तीन दिन से बुखार है। तापमान 102 डिग्री है।"
gen Lekha hi_fever_saadhe.wav "तापमान साढ़े उनतालीस डिग्री है और नब्ज़ एक सौ बीस है।"
ls -l *.wav
